version: '3'

services:
  mymongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mymongo_network
    ports:
      - "17017:27017"
    volumes:
      - ./data/mongodb_data:/data/db
      - ./data/configdb:/data/configdb

  mymongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mymongo
    networks:
      - mymongo_network
    ports:
      - "17018:8081"
    depends_on:
      - mymongo

networks:
  mymongo_network