version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 17017:27017
    networks:
      - mymongo_network
    volumes:
      - ./data/mongodb_data:/data/db
      - ./data/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongodb
    ports:
      - 17018:8081
    networks:
      - mymongo_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

networks:
  mymongo_network: