apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: myservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: myservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: username
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: password
        volumeMounts:
        - name: mongo-1
          mountPath: "/data/db"
        - name: mongo-2
          mountPath: "/data/configdb"
      volumes:
      - name: mongo-1
        persistentVolumeClaim:
          claimName: mongo-1
      - name: mongo-2
        persistentVolumeClaim:
          claimName: mongo-2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: myservice
spec:
  ports:
  - port: 27017
  selector:
    app: mongo
  type: ClusterIP
